#!/usr/bin/env python3
from __future__ import annotations

import html
import json
import re
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "_site"
DOMAIN = "https://estrechoormuz.com"

BLOCKED_EXTENSIONS = {
    ".py", ".json", ".yml", ".yaml", ".md", ".map", ".toml",
    ".lock", ".ini", ".cfg", ".sh", ".bat", ".ps1", ".zip",
}
BLOCKED_NAMES = {
    "README", "README.md", "CHANGELOG.md", "INSTRUCCIONES.txt",
    "INSTRUCCIONES_SUBIDA.txt", "LEEME.txt", "LEEME_INSTALACION.md",
    "llms.txt", "humans.txt", "CNAME",
}
BLOCKED_HTML = {"social-studio.html", "en-social-studio.html"}
BLOCKED_DYNAMIC_JS = {
    "app.js", "daily-brief.js", "evidence-ui.js",
    "evidence-archive.js", "operational-v7.js",
}

REPLACEMENTS = (
    ("Código y metodología auditables", "Metodología pública · Fuentes verificables"),
    ("Auditable code and methodology", "Public methodology · Verifiable sources"),
    ("API JSON", "Metodología"),
    ("Developer data", "Documentación"),
    ("Datos para desarrolladores", "Documentación"),
    ("Actualización automática", "Seguimiento continuo"),
    ("Automatic updates", "Continuous monitoring"),
    ("actualización automática", "seguimiento continuo"),
    ("automatic update", "continuous monitoring"),
    ("actualizado automáticamente", "actualizado de forma continua"),
    ("updated automatically", "continuously updated"),
    ("motor de decisión", "sistema editorial de verificación"),
    ("decision engine", "editorial verification system"),
    ("Generado por IA", "Equipo editorial de Estrecho Ormuz"),
    ("Generated by AI", "Estrecho Ormuz Editorial Team"),
    ("Generado con IA", "Equipo editorial de Estrecho Ormuz"),
    ("AI-generated", "Estrecho Ormuz Editorial Team"),
    ("Inteligencia artificial", "herramientas internas de análisis"),
    ("Artificial intelligence", "internal analysis tools"),
    ("inteligencia artificial", "herramientas internas de análisis"),
    ("artificial intelligence", "internal analysis tools"),
)

INTERNAL_LINK_RE = re.compile(
    r'<a\b[^>]*href=["\']/?(?:status|history|sources|config|daily-brief|'
    r'social-drafts|journal-latest|journal-state|journal-health|'
    r'operational-intelligence|source-aliases|evidence-archive)\.json'
    r'(?:\?[^"\']*)?["\'][^>]*>.*?</a>',
    re.I | re.S,
)

GITHUB_LINK_RE = re.compile(
    r'<a\b[^>]*href=["\']https?://(?:www\.)?(?:github\.com|raw\.githubusercontent\.com)/'
    r'ElPtoWalter/estado-del-estrecho-de-Ormuz[^"\']*["\'][^>]*>.*?</a>',
    re.I | re.S,
)

BLOCKED_SCRIPT_RE = re.compile(
    r'<script\b[^>]*src=["\']/?(?:app|daily-brief|evidence-ui|evidence-archive|operational-v7)\.js'
    r'(?:\?[^"\']*)?["\'][^>]*>\s*</script>',
    re.I | re.S,
)

def load_json(name: str, default: Any) -> Any:
    path = ROOT / name
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return default

def text(value: Any, fallback: str = "—") -> str:
    out = str(value or "").strip()
    return out or fallback

def esc(value: Any, fallback: str = "—") -> str:
    return html.escape(text(value, fallback), quote=True)

def parse_dt(value: Any):
    raw = str(value or "").strip()
    if not raw:
        return None
    try:
        dt = datetime.fromisoformat(raw.replace("Z", "+00:00"))
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt.astimezone(timezone.utc)
    except ValueError:
        return None

def human_date(value: Any, lang: str) -> str:
    dt = parse_dt(value)
    if not dt:
        return "—"
    return dt.strftime("%d/%m/%Y · %H:%M UTC" if lang == "es" else "%Y-%m-%d · %H:%M UTC")

def replace_element(document: str, element_id: str, content: str) -> str:
    pattern = re.compile(
        rf'(<(?P<tag>[A-Za-z0-9]+)\b[^>]*\bid=["\']{re.escape(element_id)}["\'][^>]*>)'
        rf'.*?(</(?P=tag)>)',
        re.I | re.S,
    )
    return pattern.sub(lambda m: m.group(1) + content + m.group(3), document, count=1)

def public_assessment(status: dict[str, Any]) -> dict[str, Any]:
    op = status.get("operational_intelligence")
    if isinstance(op, dict) and op.get("state"):
        return op
    separate = load_json("operational-intelligence.json", {})
    if isinstance(separate, dict) and separate.get("state"):
        return separate
    return {
        "label_es": status.get("operational_label_es") or status.get("status") or "INCIERTO",
        "label_en": status.get("operational_label_en") or status.get("status") or "UNCERTAIN",
        "operational_label_es": status.get("operational_label_es") or "",
        "operational_label_en": status.get("operational_label_en") or "",
        "summary_es": status.get("summary_es") or "",
        "summary_en": status.get("summary_en") or "",
        "confidence": status.get("confidence") or "BAJA",
        "generated_at": status.get("checked_at"),
        "latest_confirmed_transit_at": (status.get("last_valid_confirmation") or {}).get("at"),
    }

def render_evidence(status: dict[str, Any], lang: str, limit: int) -> str:
    items = status.get("evidence")
    if not isinstance(items, list):
        items = []
    cards = []
    for item in items[:limit]:
        if not isinstance(item, dict):
            continue
        cards.append(
            '<article class="evidence-card">'
            f'<div class="evidence-meta"><span>{esc(item.get("signal"), "Evidencia" if lang=="es" else "Evidence")}</span>'
            f'<time>{esc(human_date(item.get("published_at"), lang))}</time></div>'
            f'<h3><a href="{esc(item.get("source_url"), "#")}" target="_blank" rel="noopener noreferrer">'
            f'{esc(item.get("title"), "Evidencia" if lang=="es" else "Evidence")}</a></h3>'
            f'<p>{esc(item.get("source_name"), "Fuente" if lang=="es" else "Source")}</p>'
            '</article>'
        )
    if cards:
        return "".join(cards)
    return (
        '<p class="empty-state">No hay evidencias recientes publicables.</p>'
        if lang == "es" else
        '<p class="empty-state">No recent publishable evidence.</p>'
    )

def render_history(history: Any, lang: str, limit: int) -> str:
    if not isinstance(history, list):
        history = []
    rows = []
    for item in history[:limit]:
        if not isinstance(item, dict):
            continue
        label = (
            item.get("operational_label_es" if lang == "es" else "operational_label_en")
            or item.get("status")
        )
        summary = item.get("summary_es" if lang == "es" else "summary_en") or ""
        rows.append(
            '<article class="timeline-item"><div class="timeline-content">'
            f'<div class="timeline-head"><strong>{esc(label)}</strong>'
            f'<time>{esc(human_date(item.get("at"), lang))}</time></div>'
            f'<p>{esc(summary, "")}</p></div></article>'
        )
    return "".join(rows) or (
        '<p class="empty-state">Sin cambios significativos archivados.</p>'
        if lang == "es" else
        '<p class="empty-state">No material changes archived.</p>'
    )

def prerender(document: str, filename: str) -> str:
    lang = "en" if filename.startswith("en-") or filename == "en.html" else "es"
    status = load_json("status.json", {})
    history = load_json("history.json", [])
    brief = load_json("daily-brief.json", {})
    if not isinstance(status, dict):
        status = {}
    assessment = public_assessment(status)

    label = assessment.get("label_es" if lang == "es" else "label_en")
    operational = assessment.get("operational_label_es" if lang == "es" else "operational_label_en")
    summary = assessment.get("summary_es" if lang == "es" else "summary_en")
    confidence = text(assessment.get("confidence"), "BAJA")
    confidence = (
        {"ALTA":"Alta","MEDIA":"Media","BAJA":"Baja"}.get(confidence, confidence)
        if lang == "es"
        else {"ALTA":"High","MEDIA":"Medium","BAJA":"Low"}.get(confidence, confidence)
    )

    for element_id, value in (
        ("statusWord", esc(label)),
        ("operationalLabel", esc(operational, "")),
        ("statusSummary", esc(summary, "")),
        ("checkedAt", esc(human_date(assessment.get("generated_at") or status.get("checked_at"), lang))),
        ("confidence", esc(confidence)),
        ("lastValidAt", esc(human_date(assessment.get("latest_confirmed_transit_at"), lang))),
    ):
        document = replace_element(document, element_id, value)

    document = replace_element(document, "evidenceList", render_evidence(status, lang, 8))
    document = replace_element(document, "evidenceArchive", render_evidence(status, lang, 20))
    document = replace_element(document, "recentHistory", render_history(history, lang, 3))
    document = replace_element(document, "historyTimeline", render_history(history, lang, 50))

    if isinstance(history, list):
        document = replace_element(document, "historyEventCount", str(len(history)))
        if history:
            document = replace_element(document, "historyLastChange", esc(human_date(history[0].get("at"), lang)))
    document = replace_element(document, "historyCurrentStatus", esc(label))

    if isinstance(brief, dict):
        suffix = "es" if lang == "es" else "en"
        values = {
            "briefDate": brief.get("date") or brief.get("generated_at"),
            "briefStatusPill": brief.get(f"status_label_{suffix}") or label,
            "briefOperational": brief.get(f"operational_label_{suffix}") or operational,
            "briefSummary": brief.get(f"summary_{suffix}") or summary,
            "briefGenerated": human_date(brief.get("generated_at"), lang),
            "briefChange": brief.get(f"change_{suffix}") or "",
        }
        for element_id, value in values.items():
            document = replace_element(document, element_id, esc(value, ""))

    return document

def sanitize_text(document: str) -> str:
    document = INTERNAL_LINK_RE.sub("", document)
    document = GITHUB_LINK_RE.sub("", document)
    document = BLOCKED_SCRIPT_RE.sub("", document)

    document = re.sub(
        r'<code>\s*(?:status|history|sources|daily-brief|operational-intelligence)\.json\s*</code>',
        "datos internos del observatorio",
        document,
        flags=re.I,
    )

    for old, new in REPLACEMENTS:
        document = document.replace(old, new)

    document = re.sub(
        r'\b(?:sistema|proceso)\s+automatizad[oa]\b',
        "sistema editorial de seguimiento",
        document,
        flags=re.I,
    )
    document = re.sub(
        r'\b(?:AI[- ]generated|generated\s+(?:by|with)\s+AI|written\s+(?:by|with)\s+AI|ChatGPT|OpenAI|LLM)\b',
        "Equipo editorial de Estrecho Ormuz",
        document,
        flags=re.I,
    )
    return document

def editorialize_jsonld(document: str) -> str:
    def patch(match):
        try:
            data = json.loads(match.group(2))
        except json.JSONDecodeError:
            return match.group(0)

        def walk(value):
            if isinstance(value, dict):
                if value.get("@type") in {"Article","NewsArticle","AnalysisNewsArticle","Report"}:
                    value["author"] = {
                        "@type": "Organization",
                        "name": "Equipo editorial de Estrecho Ormuz",
                        "url": DOMAIN + "/sobre.html",
                    }
                    value["publisher"] = {
                        "@type": "Organization",
                        "name": "Estrecho Ormuz",
                        "url": DOMAIN + "/",
                    }
                for k in list(value):
                    value[k] = walk(value[k])
            elif isinstance(value, list):
                value = [walk(v) for v in value]
            return value

        data = walk(data)
        return match.group(1) + json.dumps(data, ensure_ascii=False, separators=(",",":")) + match.group(3)

    return re.sub(
        r'(<script\b[^>]*type=["\']application/ld\+json["\'][^>]*>)(.*?)(</script>)',
        patch,
        document,
        flags=re.I | re.S,
    )

def add_signature(document: str, filename: str) -> str:
    if "PROFESSIONAL_EDITORIAL_SIGNATURE_V9" in document:
        return document
    if not re.search(r'"@type"\s*:\s*"(?:Article|NewsArticle|AnalysisNewsArticle|Report)"', document, re.I):
        return document
    lang = "en" if filename.startswith("en-") or filename == "en.html" else "es"
    block = (
        '<div class="editorial-signature-v9"><span>Publicación</span>'
        '<strong>Equipo editorial de Estrecho Ormuz</strong>'
        '<small>Fuentes contrastadas · Metodología pública · Política de correcciones</small></div>'
        if lang == "es" else
        '<div class="editorial-signature-v9"><span>Published by</span>'
        '<strong>Estrecho Ormuz Editorial Team</strong>'
        '<small>Cross-checked sources · Public methodology · Corrections policy</small></div>'
    )
    main = re.search(r"<main\b[^>]*>", document, re.I)
    if main:
        return document[:main.end()] + "\n<!-- PROFESSIONAL_EDITORIAL_SIGNATURE_V9 -->\n" + block + document[main.end():]
    return document

def sanitize_html(document: str, filename: str) -> str:
    document = prerender(document, filename)
    document = sanitize_text(document)
    document = editorialize_jsonld(document)
    document = add_signature(document, filename)
    document = re.sub(r'\s*<link\b[^>]*rel=["\']manifest["\'][^>]*>\s*', "\n", document, flags=re.I)
    if filename != "404.html" and "/public-ui.min.js" not in document:
        document = re.sub(
            r"</body>",
            '<script defer src="/public-ui.min.js"></script>\n</body>',
            document,
            count=1,
            flags=re.I,
        )
    if "/professional-v9.css" not in document:
        document = re.sub(
            r"</head>",
            '<link rel="stylesheet" href="/professional-v9.css">\n</head>',
            document,
            count=1,
            flags=re.I,
        )
    return document

PUBLIC_UI = '''(()=>{"use strict";document.addEventListener("click",e=>{const b=e.target.closest(".nav-toggle");if(b){const n=document.getElementById("site-nav"),x=b.getAttribute("aria-expanded")==="true";b.setAttribute("aria-expanded",String(!x));n&&n.classList.toggle("is-open",!x);return}const m=e.target.closest("[data-load-marine-map]");if(m){const c=document.getElementById("marineMapContainer"),p=document.getElementById("marineMapPlaceholder"),s=document.getElementById("marineMapStatus");if(!c||c.dataset.loaded==="1")return;c.dataset.loaded="1";if(p)p.hidden=true;const f=document.createElement("iframe");f.title=document.documentElement.lang==="en"?"Live maritime traffic context":"Contexto de tráfico marítimo en directo";f.loading="lazy";f.referrerPolicy="strict-origin-when-cross-origin";f.src="https://www.marinetraffic.com/en/ais/embed/zoom:6/centery:25.8/centerx:57.7/maptype:4/shownames:false";f.style.cssText="width:100%;height:540px;border:0";c.appendChild(f);if(s)s.textContent=document.documentElement.lang==="en"?"External maritime map loaded.":"Mapa marítimo externo cargado.";}});const y=document.getElementById("currentYear");if(y)y.textContent=String(new Date().getFullYear());})();'''

PUBLIC_CSS = '''
.editorial-signature-v9{display:flex;flex-wrap:wrap;gap:.45rem 1rem;align-items:center;margin:0 auto 1.4rem;max-width:1180px;padding:.85rem 1rem;border:1px solid var(--line);border-radius:14px;background:rgba(255,255,255,.025);font-size:.82rem}
.editorial-signature-v9 span,.editorial-signature-v9 small{color:var(--muted)}
.editorial-signature-v9 strong{font-size:.88rem}
'''

HEADERS = '''/*
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=(), browsing-topics=()
  X-Frame-Options: SAMEORIGIN
  Content-Security-Policy: default-src 'self' https: data: blob:; base-uri 'self'; object-src 'none'; form-action 'self' mailto:; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' https: data: blob:; connect-src 'self' https:; frame-src https:; font-src 'self' https: data:; upgrade-insecure-requests

/widget.html
  ! X-Frame-Options
  Content-Security-Policy: default-src 'self' https: data: blob:; base-uri 'self'; object-src 'none'; frame-ancestors *; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' https: data: blob:

/en-widget.html
  ! X-Frame-Options
  Content-Security-Policy: default-src 'self' https: data: blob:; base-uri 'self'; object-src 'none'; frame-ancestors *; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' https: data: blob:

https://:project.pages.dev/*
  X-Robots-Tag: noindex

https://:version.:project.pages.dev/*
  X-Robots-Tag: noindex
'''

REDIRECTS = '''/status.json /404.html 404
/history.json /404.html 404
/sources.json /404.html 404
/config.json /404.html 404
/daily-brief.json /404.html 404
/daily-brief-archive.json /404.html 404
/social-drafts.json /404.html 404
/source-aliases.json /404.html 404
/operational-intelligence.json /404.html 404
/operational-intelligence-history.json /404.html 404
/journal-latest.json /404.html 404
/journal-state.json /404.html 404
/journal-health.json /404.html 404
/journal-archive.json /404.html 404
/*.py /404.html 404
/*.yml /404.html 404
/*.yaml /404.html 404
/*.md /404.html 404
'''

def copy_asset(path: Path) -> bool:
    if path.name in BLOCKED_NAMES or path.suffix.lower() in BLOCKED_EXTENSIONS:
        return False
    if path.name in BLOCKED_DYNAMIC_JS or path.name.startswith("."):
        return False
    if path.name.startswith(("test_","install_","prepare_","build_","professionalize_")):
        return False
    return path.suffix.lower() in {
        ".css",".js",".png",".jpg",".jpeg",".webp",".svg",".ico",".xml",".txt"
    }

def write_sitemap():
    urls = []
    for path in sorted(OUT.rglob("*.html")):
        rel = path.relative_to(OUT).as_posix()
        if rel == "404.html" or rel in BLOCKED_HTML:
            continue
        body = path.read_text(encoding="utf-8")
        if re.search(r'<meta\b[^>]*name=["\']robots["\'][^>]*noindex', body, re.I):
            continue
        urls.append(DOMAIN + ("/" if rel == "index.html" else "/" + rel))
    today = datetime.now(timezone.utc).date().isoformat()
    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for url in urls:
        lines.append(f"  <url><loc>{html.escape(url)}</loc><lastmod>{today}</lastmod></url>")
    lines.append("</urlset>")
    (OUT/"sitemap.xml").write_text("\n".join(lines)+"\n", encoding="utf-8")

def audit():
    errors = []
    for path in OUT.rglob("*"):
        if not path.is_file():
            continue
        rel = path.relative_to(OUT).as_posix()
        if path.suffix.lower() in BLOCKED_EXTENSIONS:
            errors.append(f"blocked extension leaked: {rel}")
        if path.name in BLOCKED_NAMES:
            errors.append(f"blocked file leaked: {rel}")
        if path.suffix.lower() in {".html",".js",".css",".xml",".txt"}:
            body = path.read_text(encoding="utf-8", errors="ignore")
            for token in (
                "raw.githubusercontent.com/ElPtoWalter",
                "github.com/ElPtoWalter/estado-del-estrecho-de-Ormuz",
                'href="/status.json"',
                'href="/history.json"',
                "GITHUB_TOKEN",
                "CLOUDFLARE_API_TOKEN",
            ):
                if token in body:
                    errors.append(f"{rel}: forbidden token {token}")
    if errors:
        print("PUBLIC BUILD AUDIT FAILED", file=sys.stderr)
        for error in errors:
            print(" -", error, file=sys.stderr)
        raise SystemExit(2)

def main():
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)

    for path in sorted(ROOT.rglob("*.html")):
        if OUT in path.parents or ".git" in path.parts or ".github" in path.parts:
            continue
        rel = path.relative_to(ROOT)
        if rel.as_posix() in BLOCKED_HTML:
            continue
        target = OUT / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(sanitize_html(path.read_text(encoding="utf-8"), path.name), encoding="utf-8")

    for path in sorted(ROOT.iterdir()):
        if not path.is_file() or not copy_asset(path):
            continue
        if path.name in {"sitemap.xml","robots.txt"}:
            continue
        shutil.copy2(path, OUT/path.name)

    for dirname in ("diario","diary","briefs","images","assets"):
        source_dir = ROOT/dirname
        if not source_dir.exists():
            continue
        for path in source_dir.rglob("*"):
            if not path.is_file():
                continue
            rel = path.relative_to(ROOT)
            target = OUT/rel
            if path.suffix.lower() == ".html":
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(sanitize_html(path.read_text(encoding="utf-8"), path.name), encoding="utf-8")
            elif copy_asset(path):
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(path, target)

    (OUT/"public-ui.min.js").write_text(PUBLIC_UI, encoding="utf-8")
    (OUT/"professional-v9.css").write_text(PUBLIC_CSS.strip()+"\n", encoding="utf-8")
    (OUT/"_headers").write_text(HEADERS.strip()+"\n", encoding="utf-8")
    (OUT/"_redirects").write_text(REDIRECTS.strip()+"\n", encoding="utf-8")
    (OUT/"robots.txt").write_text(
        "User-agent: *\nAllow: /\n\nSitemap: https://estrechoormuz.com/sitemap.xml\n",
        encoding="utf-8",
    )
    write_sitemap()
    audit()
    print("Professional Security V9 public build created successfully.")
    print("No Python, JSON, workflows, configuration or internal engine files were published.")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
