#!/usr/bin/env python3
# Estrecho Ormuz — public-only professional build.
# Internal JSON, Python, workflows and data-fetching JS are never copied to _site.

from __future__ import annotations
import html
import json
import re
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path
from publication_quality import apply_policy
from monitor_report import build_reports
from typing import Any

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "_site"
DOMAIN = "https://estrechoormuz.com"

PRIVATE_EXTENSIONS = {
    ".py", ".json", ".yml", ".yaml", ".md", ".map", ".toml",
    ".lock", ".ini", ".cfg", ".sh", ".bat", ".ps1", ".zip",
}
PRIVATE_PREFIXES = (
    "README", "LEEME", "INSTRUCCIONES", "CHANGELOG",
    "test_", "install_", "prepare_", "build_", "professionalize_", "fix_",
)
BLOCKED_HTML = {"social-studio.html", "en-social-studio.html"}
PRIVATE_ENDPOINT_RE = re.compile(
    r"(?:status|history|config|sources|daily-brief|daily-brief-archive|"
    r"social-drafts|source-aliases|evidence-archive|operational-intelligence|"
    r"operational-intelligence-history|journal-latest|journal-state|journal-health|"
    r"journal-archive)\.json",
    re.I,
)
PRIVATE_ENDPOINT_URL_RE = re.compile(
    r"https?://(?:www\.)?estrechoormuz\.com/(?:status|history|config|sources|daily-brief|"
    r"daily-brief-archive|social-drafts|source-aliases|evidence-archive|"
    r"operational-intelligence|operational-intelligence-history|journal-latest|"
    r"journal-state|journal-health|journal-archive)\.json",
    re.I,
)

NO_ADS_PAGES = {
    "404.html", "alertas.html", "en-alerts.html",
    "aviso-legal.html", "en-legal.html", "privacidad.html", "en-privacy.html",
    "cookies.html", "en-cookies.html", "contacto.html", "en-contact.html",
    "publicidad.html", "en-advertising.html", "media-kit.html", "en-media-kit.html",
    "historial.html", "en-history.html", "evidencias.html", "en-evidence.html",
    "embed.html", "en-embed.html", "widget.html", "en-widget.html",
}
ADSENSE_BLOCK_RE = re.compile(
    r"\s*<!-- ADSENSE_V11_3_START -->.*?<!-- ADSENSE_V11_3_END -->\s*",
    re.I | re.S,
)
ADSENSE_SCRIPT_RE = re.compile(
    r'\s*<script\b[^>]*src=["\'][^"\']*pagead2\.googlesyndication\.com/'
    r'pagead/js/adsbygoogle\.js[^"\']*["\'][^>]*>\s*</script>\s*',
    re.I | re.S,
)

PRO_LANGUAGE = (
    ("Código y metodología auditables", "Metodología pública · Fuentes verificables"),
    ("Auditable code and methodology", "Public methodology · Verifiable sources"),
    ("Código y metodología", "Metodología y fuentes"),
    ("Code and methodology", "Methodology and sources"),
    ("Actualización automática", "Seguimiento continuo"),
    ("Automatic updates", "Continuous monitoring"),
    ("Automatic update", "Continuous monitoring"),
    ("actualización automática", "seguimiento continuo"),
    ("automatic update", "continuous monitoring"),
    ("actualizada automáticamente", "bajo seguimiento continuo"),
    ("actualizado automáticamente", "bajo seguimiento continuo"),
    ("updated automatically", "under continuous monitoring"),
    ("Seguimiento automatizado y prudente", "Seguimiento editorial continuo y prudente"),
    ("Automated, cautious monitoring", "Continuous, cautious editorial monitoring"),
    ("Sistema operativo", "Seguimiento activo"),
    ("System operational", "Monitoring active"),
    ("motor de decisión", "criterio editorial de verificación"),
    ("decision engine", "editorial verification criteria"),
    ("motor de estado", "criterio editorial"),
    ("status engine", "editorial criteria"),
    ("Generado por IA", "Publicación de Estrecho Ormuz"),
    ("Generated by AI", "Published by Estrecho Ormuz"),
    ("Generado con IA", "Publicación de Estrecho Ormuz"),
    ("AI-generated", "Published by Estrecho Ormuz"),
    ("Inteligencia artificial", "herramientas internas de análisis"),
    ("Artificial intelligence", "internal analysis tools"),
    ("inteligencia artificial", "herramientas internas de análisis"),
    ("artificial intelligence", "internal analysis tools"),
    ("Redacción automatizada con control de consistencia", "Estrecho Ormuz · selección automática"),
    ("Automated newsroom with consistency checks", "Estrecho Ormuz · automated selection"),
    ("Crónica diaria automática y trazable", "Crónica diaria · fuentes verificables"),
    ("Daily automated, traceable briefing", "Daily briefing · verifiable sources"),
    ("API pública", "servicio público"),
    ("public API", "public service"),
    ("Public API", "Public service"),
    ("API vigente", "información vigente"),
    ("live API", "current information"),
    ("JSON API", "Metodología y fuentes"),
    ("API JSON", "Metodología y fuentes"),
    ("Datos para desarrolladores", "Documentación editorial"),
    ("Developer data", "Editorial documentation"),
    ("El motor ejecuta comprobaciones automáticas periódicas. La hora exacta del último ciclo aparece en el panel principal.", "El observatorio mantiene un seguimiento continuo. La hora de la última comprobación aparece en el panel principal."),
    ("The engine runs periodic automated checks. The exact time of the latest cycle appears in the main panel.", "The observatory is continuously monitored. The time of the latest verification appears in the main panel."),
    ("La API y el RSS son públicos para consulta razonable. Cita a Estrecho Ormuz y enlaza la metodología cuando reutilices la clasificación.", "Sí. Puedes citar las conclusiones públicas de Estrecho Ormuz, indicando la fuente y enlazando la metodología. El RSS está disponible para seguir nuevas publicaciones."),
    ("The API and RSS are public for reasonable use. Credit Estrecho Ormuz and link to the methodology when reusing the classification.", "Yes. You may cite Estrecho Ormuz\'s public conclusions with attribution and a link to the methodology. RSS is available for following new publications."),
)

METHOD_ES = (
    "Publicación de Estrecho Ormuz basada en fuentes marítimas, energéticas y "
    "periodísticas contrastadas, junto con los datos propios del observatorio. "
    "Los hechos operativos, las declaraciones, la interpretación y las señales "
    "de mercado se presentan de forma diferenciada y con fuentes verificables."
)
METHOD_EN = (
    "Published by Estrecho Ormuz using cross-checked maritime, energy and "
    "journalistic sources together with the observatory's own data. Operational "
    "facts, statements, interpretation and market signals are presented separately "
    "with verifiable sources."
)

def load_json(name: str, default: Any) -> Any:
    try:
        return json.loads((ROOT / name).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return default

def value_text(value: Any, fallback: str = "—") -> str:
    text = str(value or "").strip()
    return text or fallback

def esc(value: Any, fallback: str = "—") -> str:
    return html.escape(value_text(value, fallback), quote=True)

def parse_dt(value: Any):
    raw = str(value or "").strip()
    if not raw:
        return None
    try:
        dt = datetime.fromisoformat(raw.replace("Z", "+00:00"))
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt.astimezone(timezone.utc)
    except ValueError:
        return None

def human_date(value: Any, lang: str) -> str:
    dt = parse_dt(value)
    if not dt:
        return "—"
    return dt.strftime("%d/%m/%Y · %H:%M UTC" if lang == "es" else "%Y-%m-%d · %H:%M UTC")

def lang_for(filename: str, document: str = "") -> str:
    language = re.search(r'<html\b[^>]*\blang=["\']([^"\']+)', document, re.I)
    if language:
        return "en" if language.group(1).lower().startswith("en") else "es"
    return "en" if filename == "en.html" or filename.startswith("en-") else "es"

def _replace_inner_html(document: str, opening_pattern: re.Pattern[str], content: str) -> str:
    """Replace inner HTML while respecting nested elements of the same tag."""
    match = opening_pattern.search(document)
    if not match:
        return document
    tag = match.group("tag")
    start_inner = match.end()
    token_re = re.compile(
        rf"<{re.escape(tag)}\b[^>]*>|</{re.escape(tag)}\s*>",
        re.I | re.S,
    )
    depth = 1
    for token in token_re.finditer(document, start_inner):
        raw = token.group(0)
        if raw.lower().startswith(f"</{tag.lower()}"):
            depth -= 1
            if depth == 0:
                return document[:start_inner] + content + document[token.start():]
        elif not raw.rstrip().endswith("/>"):
            depth += 1
    raise RuntimeError(f"No matching closing tag for <{tag}>")

def replace_element(document: str, element_id: str, content: str) -> str:
    opening = re.compile(
        rf'<(?P<tag>[A-Za-z0-9]+)\b[^>]*\bid=["\']{re.escape(element_id)}["\'][^>]*>',
        re.I | re.S,
    )
    return _replace_inner_html(document, opening, content)

def replace_data_attr_content(document: str, attr: str, content: str) -> str:
    opening = re.compile(
        rf'<(?P<tag>[A-Za-z0-9]+)\b[^>]*\b{re.escape(attr)}(?:=["\'][^"\']*["\'])?[^>]*>',
        re.I | re.S,
    )
    return _replace_inner_html(document, opening, content)


def set_element_attrs(document: str, element_id: str, **attrs: str) -> str:
    pattern = re.compile(rf'<[A-Za-z0-9]+\b[^>]*\bid=["\']{re.escape(element_id)}["\'][^>]*>', re.I)
    def patch(match):
        tag = match.group(0)
        for key, value in attrs.items():
            key = key.replace("_", "-")
            tag = re.sub(rf'\s+{re.escape(key)}(?:=["\'][^"\']*["\'])?(?=\s|>)', "", tag, flags=re.I)
            tag = tag[:-1] + f' {key}="{html.escape(str(value), quote=True)}">'
        return tag
    return pattern.sub(patch, document, count=1)


def archive_items(status: dict[str, Any]) -> list[dict[str, Any]]:
    items, seen = [], set()
    for item in (status.get("evidence_archive") or []) + (status.get("evidence") or []):
        if not isinstance(item, dict) or not item.get("title"):
            continue
        key = tuple(str(item.get(k) or "").strip().casefold() for k in ("source_name", "title", "source_url"))
        if key in seen:
            continue
        seen.add(key)
        items.append(item)
    return sorted(items, key=lambda x: str(x.get("published_at") or x.get("observed_at") or ""), reverse=True)


def render_archive(document: str, status: dict[str, Any], lang: str) -> str:
    if 'id="archiveList"' not in document:
        return document
    items = archive_items(status)
    sources = sorted({str(x.get("source_name") or "—") for x in items}, key=str.casefold)
    cards = []
    for item in items:
        source = str(item.get("source_name") or "—")
        url = str(item.get("source_url") or "")
        title = esc(item.get("title"))
        link = f'<a href="{esc(url)}" target="_blank" rel="noopener noreferrer nofollow">{title}</a>' if url.startswith(("https://", "http://")) else title
        cards.append(
            f'<article class="archive-item" data-archive-item data-source="{esc(source)}">'
            f'<div class="archive-date"><span>{"Publicada" if lang == "es" else "Published"}</span>'
            f'<strong>{esc(human_date(item.get("published_at") or item.get("observed_at"), lang))}</strong></div>'
            f'<div class="archive-item-main"><div class="archive-badges"><span class="archive-badge">{esc(item.get("signal"))}</span></div>'
            f'<h2>{link}</h2><p class="archive-item-source">{esc(source)}</p></div></article>'
        )
    empty = "No hay evidencias que coincidan con estos filtros." if lang == "es" else "No evidence matches these filters."
    document = replace_element(document, "archiveList", "".join(cards) + f'<p class="archive-empty" data-archive-empty{ " hidden" if items else ""}>{empty}</p>')
    document = set_element_attrs(document, "archiveList", **{"class": "archive-list"})
    options = '<option value="all">' + ("Todas las fuentes" if lang == "es" else "All sources") + '</option>'
    options += "".join(f'<option value="{esc(source)}">{esc(source)}</option>' for source in sources)
    document = replace_element(document, "archiveSource", options)
    for key, value in {
        "archiveMetricChecked": human_date(status.get("checked_at"), lang),
        "archiveMetricDays": str((status.get("diagnostics") or {}).get("evidence_archive_days", 14)) + (" días" if lang == "es" else " days"),
        "archiveMetricCount": len(items), "archiveMetricSources": len(sources),
        "archiveSummary": f'{len(items)} ' + ("resultados" if lang == "es" else "results"),
    }.items():
        document = replace_element(document, key, html.escape(str(value)))
    return document

def set_status_hero_class(document: str, family: str) -> str:
    state_class = {
        "OPEN": "is-open",
        "CLOSED": "is-closed",
    }.get(str(family or "").upper(), "is-uncertain")

    tag_re = re.compile(
        r'<(?P<tag>[A-Za-z0-9]+)\b(?=[^>]*\bid=["\']statusHero["\'])[^>]*>',
        re.I | re.S,
    )
    match = tag_re.search(document)
    if not match:
        return document

    opening = match.group(0)
    class_re = re.compile(r'\bclass=["\']([^"\']*)["\']', re.I)
    class_match = class_re.search(opening)
    classes = class_match.group(1).split() if class_match else []
    classes = [c for c in classes if c not in {"is-loading", "is-open", "is-closed", "is-uncertain", "is-provisional"}]
    classes.append(state_class)
    class_value = " ".join(dict.fromkeys(classes))

    if class_match:
        patched_opening = opening[:class_match.start()] + f'class="{class_value}"' + opening[class_match.end():]
    else:
        patched_opening = opening[:-1] + f' class="{class_value}">'
    return document[:match.start()] + patched_opening + document[match.end():]

def public_assessment(status: dict[str, Any]) -> dict[str, Any]:
    op = status.get("operational_intelligence")
    if isinstance(op, dict) and op.get("state"):
        return op
    separate = load_json("operational-intelligence.json", {})
    if isinstance(separate, dict) and separate.get("state"):
        return separate
    return {
        "family": (
            "OPEN" if status.get("status") == "ABIERTO"
            else "CLOSED" if status.get("status") == "CERRADO"
            else "UNKNOWN"
        ),
        "label_es": status.get("operational_label_es") or status.get("status") or "INCIERTO",
        "label_en": status.get("operational_label_en") or status.get("status") or "UNCERTAIN",
        "operational_label_es": status.get("operational_label_es") or "",
        "operational_label_en": status.get("operational_label_en") or "",
        "summary_es": status.get("summary_es") or "",
        "summary_en": status.get("summary_en") or "",
        "confidence": status.get("confidence") or "BAJA",
        "generated_at": status.get("checked_at"),
        "latest_confirmed_transit_at": (status.get("last_valid_confirmation") or {}).get("at"),
    }

def render_evidence(status: dict[str, Any], lang: str, limit: int) -> str:
    items = status.get("evidence")
    if not isinstance(items, list):
        items = []
    cards = []
    for item in items[:limit]:
        if not isinstance(item, dict):
            continue
        cards.append(
            '<article class="evidence-card">'
            f'<div class="evidence-meta"><span>{esc(item.get("signal"), "Evidencia" if lang=="es" else "Evidence")}</span>'
            f'<time>{esc(human_date(item.get("published_at"), lang))}</time></div>'
            f'<h3><a href="{esc(item.get("source_url"), "#")}" target="_blank" rel="noopener noreferrer">'
            f'{esc(item.get("title"), "Evidencia" if lang=="es" else "Evidence")}</a></h3>'
            f'<p>{esc(item.get("source_name"), "Fuente" if lang=="es" else "Source")}</p>'
            '</article>'
        )
    return "".join(cards) or (
        '<p class="empty-state">No hay evidencias recientes publicables.</p>'
        if lang == "es" else
        '<p class="empty-state">No recent publishable evidence.</p>'
    )

def render_history(history: Any, lang: str, limit: int) -> str:
    if not isinstance(history, list):
        history = []
    rows = []
    for item in history[:limit]:
        if not isinstance(item, dict):
            continue
        label = (
            item.get("operational_label_es" if lang == "es" else "operational_label_en")
            or item.get("status")
        )
        summary = item.get("summary_es" if lang == "es" else "summary_en") or ""
        raw_status = str(item.get("status") or "").upper()
        timeline_class = (
            "is-open" if raw_status == "ABIERTO"
            else "is-closed" if raw_status == "CERRADO"
            else "is-uncertain"
        )
        rows.append(
            f'<article class="timeline-item {timeline_class}"><div class="timeline-marker" aria-hidden="true"></div><div class="timeline-content">'
            f'<div class="timeline-head"><strong>{esc(label)}</strong>'
            f'<time>{esc(human_date(item.get("at"), lang))}</time></div>'
            f'<p>{esc(summary, "")}</p></div></article>'
        )
    return "".join(rows) or (
        '<p class="empty-state">Sin cambios significativos archivados.</p>'
        if lang == "es" else
        '<p class="empty-state">No material changes archived.</p>'
    )

def prerender(document: str, filename: str) -> str:
    lang = lang_for(filename, document)
    status = load_json("status.json", {})
    history = load_json("history.json", [])
    brief = load_json("daily-brief.json", {})
    if not isinstance(status, dict):
        status = {}
    assessment = public_assessment(status)
    document = set_status_hero_class(document, assessment.get("family"))

    label = assessment.get("label_es" if lang == "es" else "label_en")
    operational = assessment.get("operational_label_es" if lang == "es" else "operational_label_en")
    summary = assessment.get("summary_es" if lang == "es" else "summary_en")
    confidence = value_text(assessment.get("confidence"), "BAJA")
    confidence_label = (
        {"ALTA": "Alta", "MEDIA": "Media", "BAJA": "Baja"}.get(confidence, confidence)
        if lang == "es"
        else {"ALTA": "High", "MEDIA": "Medium", "BAJA": "Low"}.get(confidence, confidence)
    )
    generated = assessment.get("generated_at") or status.get("checked_at")
    latest = assessment.get("latest_confirmed_transit_at")

    for element_id, value in (
        ("statusWord", esc(label)),
        ("operationalLabel", esc(operational, "")),
        ("statusSummary", esc(summary, "")),
        ("checkedAt", esc(human_date(generated, lang))),
        ("confidence", esc(confidence_label)),
        ("lastValidAt", esc(human_date(latest, lang))),
    ):
        document = replace_element(document, element_id, value)

    document = replace_element(document, "evidenceList", render_evidence(status, lang, 8))
    document = replace_element(document, "evidenceArchive", render_evidence(status, lang, 20))
    document = replace_element(document, "recentHistory", render_history(history, lang, 3))
    document = replace_element(document, "historyTimeline", render_history(history, lang, 50))
    document = render_archive(document, status, lang)

    diagnostics = status.get("diagnostics") or {}
    counts = (diagnostics.get("independent_sources") or {}).values()
    verified = status.get("verification_ok") is True
    stale = bool(status.get("stale"))
    system = (("Comprobación incompleta" if lang == "es" else "Incomplete verification") if not verified else
              ("Datos pendientes de actualización" if lang == "es" else "Data awaiting update") if stale else
              ("Seguimiento activo" if lang == "es" else "Monitoring active"))
    for key, value in {
        "verificationProviders": len(diagnostics.get("providers_ok") or []),
        "verificationSources": max((int(x) for x in counts if isinstance(x, (int, float))), default=0),
        "verificationSignals": diagnostics.get("signals_considered", "—"),
        "verificationFreshness": human_date(status.get("checked_at"), lang),
        "systemStatus": system,
    }.items():
        document = replace_element(document, key, html.escape(str(value)))
    document = set_element_attrs(document, "systemStatus", **{"class": "system-status " + ("is-error" if not verified else "is-warning" if stale else "is-operational")})
    document = set_element_attrs(document, "verificationFreshness", data_checked_at=str(status.get("checked_at") or ""))

    if isinstance(history, list):
        document = replace_element(document, "historyEventCount", str(len(history)))
        document = replace_element(document, "historyCount", str(len(history)))
        if history:
            document = replace_element(document, "historyLastChange", esc(human_date(history[0].get("at"), lang)))
    document = replace_element(document, "historyCurrentStatus", esc(label))

    if isinstance(brief, dict):
        suffix = "es" if lang == "es" else "en"
        for element_id, value in {
            "briefDate": brief.get("date") or brief.get("generated_at"),
            "briefStatusPill": brief.get(f"status_label_{suffix}") or label,
            "briefOperational": brief.get(f"operational_label_{suffix}") or operational,
            "briefSummary": brief.get(f"summary_{suffix}") or summary,
            "briefGenerated": human_date(brief.get("generated_at"), lang),
            "briefChange": brief.get(f"change_{suffix}") or "",
            "briefConfidence": (brief.get("confidence_label") or {}).get(lang) or brief.get("confidence") or "—",
        }.items():
            document = replace_element(document, element_id, esc(value, ""))
        document = replace_element(
            document, "briefRisks",
            "".join(f"<li>{esc(item)}</li>" for item in (brief.get(f"risks_{suffix}") or [])),
        )
        document = replace_element(document, "briefEvidence", render_evidence({"evidence": brief.get("evidence") or []}, lang, 5))
        document = replace_element(
            document, "briefWatch",
            "".join(f"<li>{esc(item)}</li>" for item in (brief.get(f"watchlist_{suffix}") or [])),
        )
        archive = load_json("daily-brief-archive.json", [])
        if isinstance(archive, dict):
            archive = archive.get("items") or []
        document = replace_element(document, "briefArchive", "".join(
            f'<article><time>{esc(item.get("date"))}</time><h3>{esc(item.get(f"operational_label_{suffix}"))}</h3><p>{esc(item.get(f"summary_{suffix}"))}</p></article>'
            for item in archive[:6] if isinstance(item, dict)
        ))
        if brief:
            document = set_element_attrs(document, "briefLoading", hidden="hidden")

    if filename in {"widget.html", "en-widget.html"}:
        document = replace_data_attr_content(document, "data-state", esc(label))
        document = replace_data_attr_content(document, "data-summary", esc(summary, ""))
        document = replace_data_attr_content(document, "data-confidence", esc(confidence_label))
        document = replace_data_attr_content(document, "data-updated", esc(human_date(generated, lang)))
        document = re.sub(
            r'<script\b[^>]*src=["\']/?widget\.js(?:\?[^"\']*)?["\'][^>]*>\s*</script>',
            '<script defer src="/public-widget.min.js"></script>',
            document, flags=re.I | re.S,
        )
    return document

def strip_private_scripts(document: str) -> str:
    document = re.sub(
        r'<script\b[^>]*src=["\']/?(?:app|daily-brief|evidence-ui|evidence-archive|'
        r'operational-v7|social-studio|widget)\.js(?:\?[^"\']*)?["\'][^>]*>\s*</script>',
        "", document, flags=re.I | re.S,
    )
    document = re.sub(
        r'<script\b(?![^>]*type=["\']application/ld\+json["\'])[^>]*>'
        r'(?:(?!</script>).)*?(?:status|history|config|sources|daily-brief|'
        r'operational-intelligence|journal-state|journal-health)\.json'
        r'(?:(?!</script>).)*?</script>',
        "", document, flags=re.I | re.S,
    )
    return document

def remove_private_links(document: str) -> str:
    document = re.sub(
        r'<a\b[^>]*href=["\'][^"\']*(?:status|history|config|sources|daily-brief|'
        r'operational-intelligence|journal-state|journal-health)\.json[^"\']*["\'][^>]*>.*?</a>',
        "", document, flags=re.I | re.S,
    )
    document = re.sub(
        r'<a\b[^>]*href=["\'][^"\']*social-studio\.html[^"\']*["\'][^>]*>.*?</a>',
        "", document, flags=re.I | re.S,
    )
    document = re.sub(
        r'<a\b[^>]*href=["\']https?://(?:www\.)?(?:github\.com|raw\.githubusercontent\.com)/'
        r'ElPtoWalter/estado-del-estrecho-de-Ormuz[^"\']*["\'][^>]*>.*?</a>',
        "", document, flags=re.I | re.S,
    )
    return document

def clean_jsonld(document: str, lang: str) -> str:
    def patch(match):
        try:
            data = json.loads(match.group(2))
        except json.JSONDecodeError:
            raw = PRIVATE_ENDPOINT_URL_RE.sub(
                DOMAIN + ("/metodologia.html" if lang == "es" else "/en-methodology.html"),
                match.group(2),
            )
            raw = PRIVATE_ENDPOINT_RE.sub(
                "datos internos del observatorio" if lang == "es" else "internal observatory data",
                raw,
            )
            return match.group(1) + raw + match.group(3)

        def walk(value):
            if isinstance(value, dict):
                if value.get("@type") == "DataDownload":
                    url = str(value.get("contentUrl") or value.get("url") or "")
                    if PRIVATE_ENDPOINT_RE.search(url):
                        return None
                if value.get("@type") in {"Article", "NewsArticle", "AnalysisNewsArticle", "Report"}:
                    value["author"] = {
                        "@type": "Organization",
                        "name": "Estrecho Ormuz",
                        "url": DOMAIN + ("/sobre.html" if lang == "es" else "/en-about.html"),
                    }
                    value["publisher"] = {"@type": "Organization", "name": "Estrecho Ormuz", "url": DOMAIN + "/"}
                main = value.get("mainEntity")
                if isinstance(main, dict):
                    main_url = str(main.get("url") or main.get("contentUrl") or "")
                    if PRIVATE_ENDPOINT_RE.search(main_url):
                        value.pop("mainEntity", None)
                for key in list(value):
                    child = value[key]
                    if key in {"url", "contentUrl"} and isinstance(child, str) and PRIVATE_ENDPOINT_RE.search(child):
                        if key == "contentUrl":
                            value.pop(key, None)
                        else:
                            value[key] = DOMAIN + ("/metodologia.html" if lang == "es" else "/en-methodology.html")
                    else:
                        patched = walk(child)
                        if patched is None and key == "distribution":
                            value.pop(key, None)
                        else:
                            value[key] = patched
            elif isinstance(value, list):
                value = [x for x in (walk(item) for item in value) if x is not None]
            elif isinstance(value, str):
                value = PRIVATE_ENDPOINT_URL_RE.sub(
                    DOMAIN + ("/metodologia.html" if lang == "es" else "/en-methodology.html"), value
                )
                value = PRIVATE_ENDPOINT_RE.sub(
                    "datos internos del observatorio" if lang == "es" else "internal observatory data", value
                )
                for old, new in PRO_LANGUAGE:
                    value = value.replace(old, new)
                value = value.replace("Informe generado automáticamente", "Informe editorial elaborado")
                value = value.replace("Report generated automatically", "Editorial report prepared")
            return value

        data = walk(data)
        return match.group(1) + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + match.group(3)

    return re.sub(
        r'(<script\b[^>]*type=["\']application/ld\+json["\'][^>]*>)(.*?)(</script>)',
        patch, document, flags=re.I | re.S,
    )

def rewrite_alerts_page(document: str, lang: str) -> str:
    if lang == "es":
        main = '''<main class="site-main" id="contenido">
<header class="page-header page-header-v4"><span class="eyebrow">Seguimiento</span><h1>RSS y seguimiento del observatorio</h1><p>Formas públicas de seguir las nuevas ediciones y consultar cómo se verifican los cambios.</p></header>
<div class="page-layout"><div class="page-content-stack">
<section class="prose-card"><h2>RSS</h2><p>El feed RSS reúne nuevas publicaciones y actualizaciones relevantes para lectores compatibles.</p><div class="code-box"><code>https://estrechoormuz.com/feed.xml</code><button class="button copy-button" data-copy="https://estrechoormuz.com/feed.xml">Copiar</button></div></section>
<section class="prose-card"><h2>Metodología</h2><p>La metodología pública explica cómo se diferencian paso físico, intensidad de tráfico, restricciones y riesgo, y qué evidencia exige cada conclusión.</p><a class="button" href="/metodologia.html">Consultar metodología</a></section>
<section class="prose-card"><h2>Fuentes</h2><p>El observatorio documenta la jerarquía y el uso de fuentes marítimas, energéticas y periodísticas.</p><a class="button" href="/fuentes.html">Consultar fuentes</a></section>
</div><aside class="page-aside"><div class="aside-card"><span class="section-kicker">Acceso rápido</span><a href="/feed.xml">RSS →</a><a href="/parte-diario.html">Parte diario →</a><a href="/contacto.html">Contacto →</a></div></aside></div>
</main>'''
    else:
        main = '''<main class="site-main" id="contenido">
<header class="page-header page-header-v4"><span class="eyebrow">Monitoring</span><h1>RSS and observatory updates</h1><p>Public ways to follow new editions and review how material changes are verified.</p></header>
<div class="page-layout"><div class="page-content-stack">
<section class="prose-card"><h2>RSS</h2><p>The RSS feed brings together new publications and relevant updates for compatible readers.</p><div class="code-box"><code>https://estrechoormuz.com/feed.xml</code><button class="button copy-button" data-copy="https://estrechoormuz.com/feed.xml">Copy</button></div></section>
<section class="prose-card"><h2>Methodology</h2><p>The public methodology explains how physical passage, traffic intensity, restrictions and risk are separated, and what evidence each conclusion requires.</p><a class="button" href="/en-methodology.html">Review methodology</a></section>
<section class="prose-card"><h2>Sources</h2><p>The observatory documents its hierarchy and use of maritime, energy and journalistic sources.</p><a class="button" href="/en-sources.html">Review sources</a></section>
</div><aside class="page-aside"><div class="aside-card"><span class="section-kicker">Quick access</span><a href="/feed.xml">RSS →</a><a href="/en-daily-brief.html">Daily brief →</a><a href="/en-contact.html">Contact →</a></div></aside></div>
</main>'''
    return re.sub(r'<main\b[^>]*>.*?</main>', main, document, count=1, flags=re.I | re.S)

def rewrite_embed_page(document: str, lang: str) -> str:
    if lang == "es":
        document = document.replace(
            "Se actualiza desde la misma API pública que alimenta el observatorio.",
            "Muestra la edición operativa vigente publicada por el observatorio."
        ).replace("Copiar código", "Copiar inserción")
    else:
        document = document.replace(
            "It updates from the same public API powering the monitor.",
            "It displays the current operational edition published by the observatory."
        ).replace("Copy code", "Copy embed")
    return re.sub(
        r'<a\b[^>]*href=["\'][^"\']*social-studio\.html[^"\']*["\'][^>]*>.*?</a>',
        "", document, flags=re.I | re.S,
    )

def rewrite_media_kit(document: str, lang: str) -> str:
    document = re.sub(
        r'<!-- ORMUZ_GROWTH_V4_MEDIA_START -->.*?<!-- ORMUZ_GROWTH_V4_MEDIA_END -->',
        "", document, flags=re.I | re.S,
    )
    if lang == "es":
        return document.replace(
            "separación absoluta entre financiación, motor de estado y conclusiones",
            "separación absoluta entre financiación, criterios editoriales y conclusiones",
        )
    return document.replace(
        "complete separation between funding, the status engine and conclusions",
        "complete separation between funding, editorial criteria and conclusions",
    )

def rewrite_evidence_page(document: str, lang: str) -> str:
    if lang == "es":
        return document.replace(
            "Los datos proceden directamente de status.json y no se editan a mano.",
            "El archivo se mantiene a partir de las evidencias verificadas por el observatorio."
        )
    return document.replace(
        "The data comes directly from status.json and is not manually edited.",
        "The archive is maintained from evidence verified by the observatory."
    )

def rewrite_data_report(document: str, lang: str) -> str:
    pairs = (
        (
            ("Informe generado automáticamente desde history.json y status.json.",
             "Informe editorial elaborado a partir del historial interno del observatorio."),
            ("Informe generado automáticamente desde datos internos del observatorio.",
             "Informe editorial elaborado a partir del historial interno del observatorio."),
            ("Los archivos fuente están enlazados y pueden descargarse sin registro.",
             "Las referencias y criterios utilizados se documentan en las páginas de fuentes y metodología."),
            ("El código no añade estimaciones ocultas ni completa datos ausentes.",
             "El procedimiento no añade estimaciones ocultas ni completa datos ausentes."),
            ("El script agrupa los valores con un contador", "El cálculo agrupa los valores"),
            ("Los valores se calculan en cada ejecución a partir de archivos públicos.",
             "Los valores se calculan a partir del historial interno conservado por el observatorio."),
        )
        if lang == "es" else
        (
            ("Report generated automatically from history.json and status.json.",
             "Editorial report prepared from the observatory's internal history."),
            ("Report generated automatically from internal observatory data.",
             "Editorial report prepared from the observatory's internal history."),
            ("The source files are publicly linked and can be downloaded without registration.",
             "References and criteria are documented on the sources and methodology pages."),
            ("The code does not insert hidden estimates or fill missing observations.",
             "The procedure does not insert hidden estimates or fill missing observations."),
            ("The script groups values with counters", "The calculation groups values"),
            ("Values are calculated on every run from public files.",
             "Values are calculated from the internal history retained by the observatory."),
        )
    )
    for old, new in pairs:
        document = document.replace(old, new)
    return document

def professional_language(document: str, lang: str) -> str:
    for old, new in PRO_LANGUAGE:
        document = document.replace(old, new)
    replacement = "datos internos del observatorio" if lang == "es" else "internal observatory data"
    document = PRIVATE_ENDPOINT_RE.sub(replacement, document)
    document = re.sub(r'\b(?:ChatGPT|OpenAI|LLM)\b', "Estrecho Ormuz", document, flags=re.I)
    document = re.sub(
        r'\b(?:sistema|proceso)\s+automatizad[oa]\b',
        "proceso editorial de seguimiento", document, flags=re.I,
    )
    document = re.sub(
        r'\bautomated\s+(?:system|process|monitoring)\b',
        "editorial monitoring process", document, flags=re.I,
    )
    return document

def strip_adsense(document: str, filename: str) -> str:
    if filename not in NO_ADS_PAGES:
        return document
    return ADSENSE_SCRIPT_RE.sub("\n", ADSENSE_BLOCK_RE.sub("\n", document))

def sanitize_html(document: str, filename: str) -> str:
    lang = lang_for(filename, document)
    document = prerender(document, filename)
    document = strip_private_scripts(document)
    document = remove_private_links(document)

    if filename in {"alertas.html", "en-alerts.html"}:
        document = rewrite_alerts_page(document, lang)
    elif filename in {"embed.html", "en-embed.html"}:
        document = rewrite_embed_page(document, lang)
    elif filename in {"media-kit.html", "en-media-kit.html"}:
        document = rewrite_media_kit(document, lang)
    elif filename in {"evidencias.html", "en-evidence.html"}:
        document = rewrite_evidence_page(document, lang)
    elif filename in {"datos-propios-monitor-ormuz.html", "en-monitor-original-data-report.html"}:
        document = rewrite_data_report(document, lang)

    document = professional_language(document, lang)
    document = clean_jsonld(document, lang)
    document = strip_adsense(document, filename)
    document = re.sub(r'\s*<link\b[^>]*rel=["\']manifest["\'][^>]*>\s*', "\n", document, flags=re.I)
    document = re.sub(
        r'<a\b[^>]*href=["\'][^"\']*social-studio\.html[^"\']*["\'][^>]*>.*?</a>',
        "", document, flags=re.I | re.S,
    )

    if (
        "PROFESSIONAL_EDITORIAL_SIGNATURE_V9" not in document
        and re.search(r'"@type"\s*:\s*"(?:Article|NewsArticle|AnalysisNewsArticle|Report)"', document, re.I)
    ):
        signature = (
            '<div class="editorial-signature-v9"><span>Publicación</span>'
            '<strong>Estrecho Ormuz</strong>'
            '<small>Fuentes enlazadas · Metodología pública · Política de correcciones</small></div>'
            if lang == "es" else
            '<div class="editorial-signature-v9"><span>Published by</span>'
            '<strong>Estrecho Ormuz</strong>'
            '<small>Linked sources · Public methodology · Corrections policy</small></div>'
        )
        main = re.search(r"<main\b[^>]*>", document, re.I)
        if main:
            document = document[:main.end()] + "\n<!-- PROFESSIONAL_EDITORIAL_SIGNATURE_V9 -->\n" + signature + document[main.end():]

    if "/public-ui.min.js" not in document:
        document = re.sub(
            r"</body>", '<script defer src="/public-ui.min.js"></script>\n</body>',
            document, count=1, flags=re.I,
        )
    if "/professional-v9.css" not in document:
        document = re.sub(
            r"</head>", '<link rel="stylesheet" href="/professional-v9.css">\n</head>',
            document, count=1, flags=re.I,
        )
    return document

PUBLIC_UI = r'''(()=>{"use strict";document.addEventListener("click",e=>{const b=e.target.closest(".nav-toggle");if(b){const n=document.getElementById("site-nav"),x=b.getAttribute("aria-expanded")==="true";b.setAttribute("aria-expanded",String(!x));n&&n.classList.toggle("is-open",!x);}});const y=document.getElementById("currentYear");if(y)y.textContent=String(new Date().getFullYear());})();'''

PUBLIC_WIDGET = r'''(()=>{"use strict";const p=new URLSearchParams(location.search),b=document.body,w=document.querySelector("[data-g4-widget]");if(p.get("theme")==="light"){b.classList.add("g4-widget-light");w&&w.classList.add("is-light")}if(p.get("compact")==="1"){b.classList.add("g4-widget-compact");w&&w.classList.add("is-compact")}const lang=document.documentElement.lang==="en"?"en":"es";const c=document.querySelector("[data-confidence-label]"),u=document.querySelector("[data-updated-label]"),v=document.querySelector("[data-view]");if(c)c.textContent=lang==="en"?"Confidence":"Confianza";if(u)u.textContent=lang==="en"?"Updated":"Actualizado";if(v){v.textContent=lang==="en"?"View evidence →":"Ver evidencias →";v.href=lang==="en"?"/en-evidence.html":"/evidencias.html"}})();'''

PUBLIC_CSS = r'''
[data-archive-item][hidden],[data-archive-empty][hidden],#briefLoading[hidden]{display:none!important}
.copy-feedback{display:block;margin-top:.5rem;font-size:.85rem;color:var(--muted)}
.editorial-signature-v9{display:flex;flex-wrap:wrap;gap:.45rem 1rem;align-items:center;margin:0 auto 1.4rem;max-width:1180px;padding:.85rem 1rem;border:1px solid var(--line);border-radius:14px;background:rgba(255,255,255,.025);font-size:.82rem}
.editorial-signature-v9 span,.editorial-signature-v9 small{color:var(--muted)}
.editorial-signature-v9 strong{font-size:.88rem}
'''

HEADERS = r'''/*
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=(), browsing-topics=()
  X-Frame-Options: SAMEORIGIN
  Content-Security-Policy: default-src 'self' https: data: blob:; base-uri 'self'; object-src 'none'; form-action 'self' mailto:; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' https: data: blob:; connect-src 'self' https:; frame-src https:; font-src 'self' https: data:; upgrade-insecure-requests

/widget.html
  ! X-Frame-Options
  Content-Security-Policy: default-src 'self' https: data: blob:; base-uri 'self'; object-src 'none'; frame-ancestors *; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' https: data: blob:

/en-widget.html
  ! X-Frame-Options
  Content-Security-Policy: default-src 'self' https: data: blob:; base-uri 'self'; object-src 'none'; frame-ancestors *; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' https: data: blob:

https://:project.pages.dev/*
  X-Robots-Tag: noindex

https://:version.:project.pages.dev/*
  X-Robots-Tag: noindex
'''

def private_name(path: Path) -> bool:
    name = path.name
    if path.suffix.lower() in PRIVATE_EXTENSIONS:
        return True
    if any(name.upper().startswith(prefix.upper()) for prefix in PRIVATE_PREFIXES):
        return True
    return name in {"CNAME", "llms.txt", "humans.txt"}

def javascript_is_private(path: Path) -> bool:
    if path.suffix.lower() != ".js":
        return False
    if path.name in {
        "app.js", "daily-brief.js", "evidence-ui.js", "evidence-archive.js",
        "operational-v7.js", "widget.js", "social-studio.js",
    }:
        return True
    try:
        body = path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return True
    return bool(PRIVATE_ENDPOINT_RE.search(body))

def copy_asset(path: Path) -> bool:
    if path.name == "monitor-records.csv":
        return True
    if private_name(path) or path.name.startswith("."):
        return False
    suffix = path.suffix.lower()
    if suffix == ".txt":
        return path.name == "ads.txt"
    if suffix == ".js" and javascript_is_private(path):
        return False
    return suffix in {".css", ".js", ".png", ".jpg", ".jpeg", ".webp", ".svg", ".ico", ".xml"}

def write_sitemap() -> None:
    urls = []
    for path in sorted(OUT.rglob("*.html")):
        rel = path.relative_to(OUT).as_posix()
        if rel == "404.html" or rel in BLOCKED_HTML:
            continue
        body = path.read_text(encoding="utf-8")
        if re.search(r'<meta\b[^>]*name=["\']robots["\'][^>]*noindex', body, re.I):
            continue
        urls.append(DOMAIN + ("/" if rel == "index.html" else "/" + rel))
    today = datetime.now(timezone.utc).date().isoformat()
    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for url in urls:
        lines.append(f"  <url><loc>{html.escape(url)}</loc><lastmod>{today}</lastmod></url>")
    lines.append("</urlset>")
    (OUT / "sitemap.xml").write_text("\n".join(lines) + "\n", encoding="utf-8")

def audit_public_build() -> None:
    errors = []
    forbidden_tokens = (
        "status.json", "history.json", "config.json", "operational-intelligence.json",
        "journal-state.json", "journal-health.json", "raw.githubusercontent.com/ElPtoWalter",
        "github.com/ElPtoWalter/estado-del-estrecho-de-Ormuz",
        "Redacción automatizada", "Automated newsroom",
        "El texto se genera automáticamente", "The text is generated automatically",
        "Puntuación de novedad", "Novelty score",
        "Crónica diaria automática", "Daily automated",
        "API pública", "Public API", "JSON API", "API JSON",
        "social-studio.html", "ChatGPT", "OpenAI",
    )

    for path in OUT.rglob("*"):
        if not path.is_file():
            continue
        rel = path.relative_to(OUT).as_posix()
        if private_name(path):
            errors.append(f"private file leaked: {rel}")
            continue
        if path.suffix.lower() == ".js" and javascript_is_private(path):
            errors.append(f"private javascript leaked: {rel}")
            continue
        if path.suffix.lower() in {".html", ".js", ".css", ".xml", ".txt"}:
            body = path.read_text(encoding="utf-8", errors="ignore")
            for token in forbidden_tokens:
                if token.lower() in body.lower():
                    errors.append(f"{rel}: forbidden public token {token!r}")

    for required in ("index.html", "en.html", "robots.txt", "sitemap.xml"):
        if not (OUT / required).exists():
            errors.append(f"missing required public file: {required}")

    for forbidden in (
        "status.json", "history.json", "config.json", "update_status.py",
        "operational-intelligence.json", "social-studio.js", "widget.js", "_redirects",
    ):
        if (OUT / forbidden).exists():
            errors.append(f"forbidden public file exists: {forbidden}")

    if errors:
        print("PUBLIC BUILD AUDIT FAILED", file=sys.stderr)
        for error in errors:
            print(" -", error, file=sys.stderr)
        raise SystemExit(2)

def main() -> int:
    build_reports(ROOT)
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)

    for path in sorted(ROOT.rglob("*.html")):
        if OUT in path.parents or ".git" in path.parts or ".github" in path.parts:
            continue
        rel = path.relative_to(ROOT)
        if rel.as_posix() in BLOCKED_HTML or path.name in BLOCKED_HTML:
            continue
        target = OUT / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(
            apply_policy(sanitize_html(path.read_text(encoding="utf-8"), path.name), rel.as_posix()),
            encoding="utf-8",
        )

    for path in sorted(ROOT.iterdir()):
        if not path.is_file() or not copy_asset(path):
            continue
        if path.name in {"sitemap.xml", "robots.txt"}:
            continue
        shutil.copy2(path, OUT / path.name)

    for dirname in ("diario", "diary", "briefs", "images", "assets"):
        source_dir = ROOT / dirname
        if not source_dir.exists():
            continue
        for path in source_dir.rglob("*"):
            if not path.is_file():
                continue
            rel = path.relative_to(ROOT)
            target = OUT / rel
            if path.suffix.lower() == ".html":
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(
                    apply_policy(sanitize_html(path.read_text(encoding="utf-8"), path.name), rel.as_posix()),
                    encoding="utf-8",
                )
            elif copy_asset(path):
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(path, target)

    (OUT / "public-ui.min.js").write_text((ROOT / "public-ui.js").read_text(encoding="utf-8"), encoding="utf-8")
    (OUT / "public-widget.min.js").write_text(PUBLIC_WIDGET, encoding="utf-8")
    (OUT / "professional-v9.css").write_text(PUBLIC_CSS.strip() + "\n", encoding="utf-8")
    (OUT / "_headers").write_text(HEADERS.strip() + "\n", encoding="utf-8")
    (OUT / "robots.txt").write_text(
        "User-agent: *\nAllow: /\n\nSitemap: https://estrechoormuz.com/sitemap.xml\n",
        encoding="utf-8",
    )
    write_sitemap()
    audit_public_build()
    print("Professional public build OK.")
    print("Private JSON, Python, workflows, internal JS and technical notes are absent from _site.")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
