#!/usr/bin/env python3
from __future__ import annotations
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent

REPLACEMENTS = (
    ("Código y metodología auditables", "Metodología pública · Fuentes verificables"),
    ("Auditable code and methodology", "Public methodology · Verifiable sources"),
    ("API JSON", "Metodología"),
    ("Developer data", "Documentación"),
    ("Datos para desarrolladores", "Documentación"),
    ("Actualización automática", "Seguimiento continuo"),
    ("Automatic updates", "Continuous monitoring"),
    ("actualización automática", "seguimiento continuo"),
    ("automatic update", "continuous monitoring"),
    ("actualizado automáticamente", "actualizado de forma continua"),
    ("updated automatically", "continuously updated"),
    ("Generado por IA", "Equipo editorial de Estrecho Ormuz"),
    ("Generated by AI", "Estrecho Ormuz Editorial Team"),
    ("Generado con IA", "Equipo editorial de Estrecho Ormuz"),
    ("AI-generated", "Estrecho Ormuz Editorial Team"),
    ("Inteligencia artificial", "herramientas internas de análisis"),
    ("Artificial intelligence", "internal analysis tools"),
)

def clean(text: str) -> str:
    for old, new in REPLACEMENTS:
        text = text.replace(old, new)
    text = re.sub(
        r'<a\b[^>]*href=["\']/?(?:status|history|sources|config|daily-brief|'
        r'operational-intelligence|journal-latest|journal-state|journal-health)\.json'
        r'(?:\?[^"\']*)?["\'][^>]*>.*?</a>',
        "",
        text,
        flags=re.I | re.S,
    )
    text = re.sub(
        r'<a\b[^>]*href=["\']https?://(?:www\.)?github\.com/ElPtoWalter/'
        r'estado-del-estrecho-de-Ormuz[^"\']*["\'][^>]*>.*?</a>',
        "",
        text,
        flags=re.I | re.S,
    )
    text = re.sub(
        r'\b(?:sistema|proceso)\s+automatizad[oa]\b',
        "sistema editorial de seguimiento",
        text,
        flags=re.I,
    )
    text = re.sub(
        r'\b(?:AI[- ]generated|generated\s+(?:by|with)\s+AI|written\s+(?:by|with)\s+AI|ChatGPT|OpenAI|LLM)\b',
        "Equipo editorial de Estrecho Ormuz",
        text,
        flags=re.I,
    )
    return text

def main():
    changed = 0
    for path in sorted(ROOT.rglob("*.html")):
        if ".git" in path.parts or "_site" in path.parts:
            continue
        original = path.read_text(encoding="utf-8")
        updated = clean(original)
        if updated != original:
            path.write_text(updated, encoding="utf-8")
            changed += 1
    print(f"Public editorial cleanup: {changed} HTML files updated.")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
